apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: socialmediaapp-django
        env:
          - name: DB_NAME
            value: 'socialmediaapp'
          - name: DB_USER
            value: 'postgres'
          - name: DB_PASSWORD
            value: 'saisakthi2008'
          - name: DB_HOST
            value: 'postgres'
          - name: DB_PORT
            value: '5432'
        ports:
          - containerPort: 8000
