"""

What is Django?
Django is a Python framework that makes it easier to create web sites using Python.
Django takes care of the difficult stuff so that you can concentrate on building your web applications.
Django emphasizes reusability of components, also referred to as DRY (Don't Repeat Yourself), and comes with ready-to-use features like login system, database connection and CRUD operations (Create Read Update Delete).


How does Django Work?
Django follows the MVT design pattern (Model View Template).

Model - The data you want to present, usually data from a database.
View - A request handler that returns the relevant template and content - based on the request from the user.
Template - A text file (like an HTML file) containing the layout of the web page, with logic on how to display the data.


--------------------------------------------------------------------------------------------------------------------------

What is an App?
An app is a web application that has a specific meaning in your project, like a home page, a contact form, or a members database.
In this tutorial we will create an app that allows us to list and register members in a database.
But first, let's just create a simple Django app that displays "Hello World!".


--------------------------------------------------------------------------------------------------------------------------

Views
Django views are Python functions that take http requests and return http response, like HTML documents.
A web page that uses Django is full of views with different tasks and missions.
Views are usually put in a file called views.py located on your app's folder.
There is a views.py in your members folder that looks like this:

from django.shortcuts import render

# Create your views here.


--------------------------------------------------------------------------------------------------------------------------

The urls.py file you just created is specific for the members application. We have to do some routing in the root directory my_tennis_club as well. 
This may seem complicated, but for now, just follow the instructions below.
There is a file called urls.py on the my_tennis_club folder, open that file and add the include module in the import statement,
and also add a path() function in the urlpatterns[] list, with arguments that will route users that comes in via 127.0.0.1:8000/.

Then your file will look like this:

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('members.urls')),
    path('admin/', admin.site.urls),
]

type : python manage.py runserver 
and you will see "hello world" in h1 tag

--------------------------------------------------------------------------------------------------------------------------

Templates
In the Django Intro page, we learned that the result should be in HTML, and it should be created in a template, so let's do that.
Create a templates folder inside the members folder, and create a HTML file named room.html.

open the views and type the following:
def hello_world(request):
    return render(request,'members/room.html')
    
this renders the html in the path we given

--------------------------------------------------------------------------------------------------------------------------


Django Models
Up until now in this tutorial, output has been static data from Python or HTML templates.
Now we will see how Django allows us to work with data, without having to change or upload files in the process.
In Django, data is created in objects, called Models, and is actually tables in a database.

Create Table (Model)
To create a model, navigate to the models.py file in the /members/ folder.
Open it, and add a Member table by creating a Member class, and describe the table fields in it:

from django.db import models

class Member(models.Model):
  firstname = models.CharField(max_length=255)
  lastname = models.CharField(max_length=255)

The first field, firstname, is a Text field, and will contain the first name of the members.
The second field, lastname, is also a Text field, with the member's last name.
Both firstname and lastname is set up to have a maximum of 255 characters.



SQLite Database
When we created the Django project, we got an empty SQLite database.
It was created in the my_tennis_club root folder, and has the filename db.sqlite3.
By default, all Models created in the Django project will be created as tables in this database.

Migrate
Now when we have described a Model in the models.py file, we must run a command to actually create the table in the database.
Navigate to the /my_tennis_club/ folder and run this command:

python manage.py makemigrations members

Django creates a file describing the changes and stores the file in the /migrations/ folder:
my_tennis_club/members/migrations/0001_initial.py:

# Generated by Django 5.1.7 on 2025-03-20 11:39

from django.db import migrations, models
class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]

    ]
Note that Django inserts an id field for your tables, which is an auto increment number (first record gets the value 1, the second record 2 etc.), 
this is the default behavior of Django, you can override it by describing your own id field.
The table is not created yet, you will have to run one more command, 
then Django will create and execute an SQL statement, based on the content of the new file in the /migrations/ folder.
Run the migrate command:
python manage.py migrate

View SQL
As a side-note: you can view the SQL statement that were executed from the migration above. All you have to do is to run this command, with the migration number:
python manage.py sqlmigrate members 0001


--------------------------------------------------------------------------------------------------------------------------

CRUD Rows: (Create Read Update Delete) 

The Members table created in the previous chapter is empty.
We will use the Python interpreter (Python shell) to add some members to it.
To open a Python shell, type this command: python manage.py shell

Steps to CRUD a record:

Step 1 : In the console, import app_name.models import class_name
Step 2 : To show all the tables available, type : Member.objects.all()
         This will give a output of all records created inside table.
Step 3 (Create) : To add a record, Object_name = Class_name(attribute1=value1, attribute2=value2, ...)
         Object_name.save()
Step 4 : To add multiple values, 
         Object_name_1 = Class_name(attribute1=value1, attribute2=value2, ...)
         Object_name_2 = Class_name(attribute1=value1, attribute2=value2, ...)
         ...
         Object_list = [Object_name_1 ,Object_name_2, ...]
         for x in Object_list:
             x.save()

Step 5 (Read) : To show all the added values : Member.objects.all().values()
Step 6 (Update) : To update a Value, variable_name = Member.objects.all()[index_of_data_you_want_to_edit]
         variable_name.attribute = new_value
         variable_name.save()
Step 7 (Delete) : To delete a value, follow the same procedure but instead of saving or assigning use, variable_name.delete()

Note: To exit from InteractiveConsole, use quit() func 

--------------------------------------------------------------------------------------------------------------------------

Create Template
After creating Models, with the fields and data we want in them, it is time to display the data in a web page.


Modify View
Next we need to make the model data available in the template. This is done in the view.
In the view we have to import the Member model, and send it to the template like this:
my_tennis_club/members/views.py:

from django.http import HttpResponse
from django.template import loader
from .models import Member

def members(request):
  mymembers = Member.objects.all().values()
  template = loader.get_template('all_members.html')
  context = {
    'mymembers': mymembers,
  }
  return HttpResponse(template.render(context, request))

The members view does the following:
Creates a mymembers object with all the values of the Member model.
Loads the all_members.html template.
Creates an object containing the mymembers object.
Sends the object to the template.
Outputs the HTML that is rendered by the template.


--------------------------------------------------------------------------------------------------------------------------

Django Add Link to Details

Details Template :
The next step in our web page will be to add a Details page, where we can list more details about a specific member.

Add Link in all-members Template :
The list in all_members.html should be clickable, and take you to the details page with the ID of the member you clicked on:

my_tennis_club/members/templates/all_members.html:
<!DOCTYPE html>
<html>
<body>
<h1>Members</h1>

<ul>
  {% for x in mymembers %}
    <li><a href="details/{{ x.id }}">{{ x.firstname }} {{ x.lastname }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

Create new View
Then create a new view in the views.py file, that will deal with incoming requests to the /details/ url:
my_tennis_club/members/views.py:

from django.http import HttpResponse
from django.template import loader
from .models import Member

def members(request):
    mymembers = Member.objects.all().values()
    template = loader.get_template('all_members.html')
    context = {
        'mymembers': mymembers,
    }
    return HttpResponse(template.render(context, request))

def details(request, id):
    x = Member.objects.get(id=id)
    template = loader.get_template('details.html')
    context = {
        'mymember': mymember,
    }
    return HttpResponse(template.render(context, request)) 



The details view does the following:

Gets the id as an argument.
Uses the id to locate the correct record in the Member table.
loads the details.html template.
Creates an object containing the member.
Sends the object to the template.
Outputs the HTML that is rendered by the template.
Add URLs
Now we need to make sure that the /details/ url points to the correct view, with id as a parameter.

Open the urls.py file and add the details view to the urlpatterns list:
my_tennis_club/members/urls.py:

from django.urls import path
from . import views

urlpatterns = [
    path('members/', views.members, name='members'),
    path('members/details/<int:id>', views.details, name='details'),
]

If you have followed all the steps on your own computer, you can see the result in your own browser: 127.0.0.1:8000/members/.
If the server is down, you have to start it again with the runserver command:
python manage.py runserver

--------------------------------------------------------------------------------------------------------------------------

Django Add Master Template

The extends Tag :
In the previous pages we created two templates, one for listing all members, and one for details about a member.
The templates have a set of HTML code that are the same for both templates.
Django provides a way of making a "parent template" that you can include in all pages to do the stuff that is the same in all pages.
Start by creating a template called master.html, with all the necessary HTML elements:
Master : 

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>
Do you see Django block Tag inside the <title> element, and the <body> element?

They are placeholders, telling Django to replace this block with content from other sources.

Modify Templates
Now the two templates (all_members.html and details.html) can use this master.html template.
This is done by including the master template with the {% extends %} tag, and inserting a title block and a content block:

Members
{% extends "master.html" %}

{% block title %}
  My Tennis Club - List of all members
{% endblock %}
{% block content %}
  <h1>Members</h1>
  
  <ul>
    {% for x in mymembers %}
      <li><a href="details/{{ x.id }}">{{ x.firstname }} {{ x.lastname }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

Details
{% extends "master.html" %}
{% block title %}
  Details about {{ mymember.firstname }} {{ mymember.lastname }}
{% endblock %}
{% block content %}
  <h1>{{ mymember.firstname }} {{ mymember.lastname }}</h1>
  
  <p>Phone {{ mymember.phone }}</p>
  <p>Member since: {{ mymember.joined_date }}</p>
  
  <p>Back to <a href="/members">Members</a></p>
  
{% endblock %}

--------------------------------------------------------------------------------------------------------------------------  

Django Add Main Index Page

Main Index Page
Our project needs a main page.
The main page will be the landing page when someone visits the root folder of the project.
Start by creating a template called main.html:

{% extends "master.html" %}
{% block title %}
  My Tennis Club
{% endblock %}
{% block content %}
  <h1>My Tennis Club</h1>

  <h3>Members</h3>
  
  <p>Check out all our <a href="members/">members</a></p>
  
{% endblock %}

Create new View
Then create a new view called main, that will deal with incoming requests to root of the project:
my_tennis_club/members/views.py:

from django.http import HttpResponse
from django.template import loader
from .models import Member


def main(request):
  template = loader.get_template('main.html')
  return HttpResponse(template.render())

  
The main view does the following:
loads the main.html template.
Outputs the HTML that is rendered by the template.
Add URL
Now we need to make sure that the root url points to the correct view.

Open the urls.py file and add the main view to the urlpatterns list:
my_tennis_club/members/urls.py:

from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('members/', views.members, name='members'),
    path('members/details/<int:id>', views.details, name='details'),
]
 
Add Link Back to Main
The members page is missing a link back to the main page, so let us add that in the all_members.html template, in the content block:

Example
my_tennis_club/members/templates/all_members.html:

{% extends "master.html" %}

{% block title %}
  My Tennis Club - List of all members
{% endblock %}


{% block content %}

  <p><a href="/">HOME</a></p>

  <h1>Members</h1>
  
  <ul>
    {% for x in mymembers %}
      <li><a href="details/{{ x.id }}">{{ x.firstname }} {{ x.lastname }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

--------------------------------------------------------------------------------------------------------------------------

Django 404 (page not found)
Page Not Found
If you try to access a page that does not exist (a 404 error), Django directs you to a built-in view that handles 404 errors.

You will learn how to customize this 404 view later in this chapter, but first, just try to request a page that does not exist.

In the browser window, type 127.0.0.1:8000/masfdfg/ in the address bar.

You will get one of two results:

1:


2:


If you got the first result, you got directed to the built-in Django 404 template.

If you got the second result, then DEBUG is set to True in your settings, and you must set it to False to get directed to the 404 template.

This is done in the settings.py file, which is located in the project folder, in our case the my_tennis_club folder, where you also have to specify the host name from where your project runs from:

ExampleGet your own Django Server
Set the debug property to False, and allow the project to run from your local host:

my_tennis_club/my_tennis_club/settings.py:

.
.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
.
.
Important: When DEBUG = False, Django requires you to specify the hosts you will allow this Django project to run from.

In production, this should be replaced with a proper domain name:

ALLOWED_HOSTS = ['yourdomain.com']

In the browser window, type 127.0.0.1:8000/masfdfg/ in the address bar, and you will get the built-in 404 template:


Customize the 404 Template
Django will look for a file named 404.html in the templates folder, and display it when there is a 404 error.

If no such file exists, Django shows the "Not Found" that you saw in the example above.

To customize this message, all you have to do is to create a file in the templates folder and name it 404.html, and fill it with whatever you want:

my_tennis_club/members/templates/404.html:

<!DOCTYPE html>
<html>
<title>Wrong address</title>
<body>

<h1>Ooops!</h1>

<h2>I cannot find the file you requested!</h2>

</body>
</html>
In the browser window, type 127.0.0.1:8000/masfdfg/ in the address bar, and you will get the customized 404 template:


Reset Debug = True
You should reset the debug property to True to continue with the tutorial.

Example
my_tennis_club/my_tennis_club/settings.py:

.
.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

--------------------------------------------------------------------------------------------------------------------------

CRUD Django-Admin :

Create User
To be able to log into the admin application, we need to create a user.
This is done by typing this command in the command view:
python manage.py createsuperuser
Which will give this prompt:
Username:
Here you must enter: username, e-mail address, (you can just pick a fake e-mail address), and password:

Username: johndoe
Email address: johndoe@dummymail.com
Password:
Password (again):
This password is too short. It must contain at least 8 characters.
This password is too common.
This password is entirely numeric.
Bypass password validation and create user anyway? [y/N]:
My password did not meet the criteria, but this is a test environment, and I choose to create user anyway, by enter y:

Bypass password validation and create user anyway? [y/N]: y
If you press [Enter], you should have successfully created a user:

Superuser created successfully.
Now start the server again:

python manage.py runserver
In the browser window, type 127.0.0.1:8000/admin/ in the address bar.

And fill in the form with the correct username and password:


Which should result in this user interface:


Here you can create, read, update, and delete groups and users, but where is the Members model?

Missing Model
The Members model is missing, as it should be, you have to tell Django which models that should be visible in the admin interface.

You will learn how to include the Members model in the next chapter.


Django Admin - Include Member
Include Member in the Admin Interface
To include the Member model in the admin interface, we have to tell Django that this model should be visible in the admin interface.

This is done in a file called admin.py, and is located in your app's folder, which in our case is the members folder.

Open it, and it should look like this:

my_tennis_club/members/admin.py:

from django.contrib import admin

# Register your models here.
Insert a couple of lines here to make the Member model visible in the admin page:

my_tennis_club/members/admin.py:

from django.contrib import admin
from .models import Member

# Register your models here.
admin.site.register(Member)
Now go back to the browser (127.0.0.1:8000/admin/) and you should get this result:


Click Members and see the five records we inserted earlier in this tutorial:


Change Display
In the list in the screenshot above, we see "Member object (1)", "Member object (2)" etc. which might not be the data you wanted to be displayed in the list.

It would be better to display "firstname" and "lastname" instead.

This can easily be done by changing some settings in the models.py and/or the admin.py files. You will learn more about this in the next chapter.


--------------------------------------------------------------------------------------------------------------------------

Django Admin - Include Member
Include Member in the Admin Interface
To include the Member model in the admin interface, we have to tell Django that this model should be visible in the admin interface.

This is done in a file called admin.py, and is located in your app's folder, which in our case is the members folder.

Open it, and it should look like this:

my_tennis_club/members/admin.py:

from django.contrib import admin

# Register your models here.
Insert a couple of lines here to make the Member model visible in the admin page:

my_tennis_club/members/admin.py:

from django.contrib import admin
from .models import Member

# Register your models here.
admin.site.register(Member)
Now go back to the browser (127.0.0.1:8000/admin/) and you should get this result:


Click Members and see the five records we inserted earlier in this tutorial:


Change Display
In the list in the screenshot above, we see "Member object (1)", "Member object (2)" etc. which might not be the data you wanted to be displayed in the list.

It would be better to display "firstname" and "lastname" instead.

This can easily be done by changing some settings in the models.py and/or the admin.py files. You will learn more about this in the next chapter.

--------------------------------------------------------------------------------------------------------------------------


Django Admin - Set Fields to Display
Make the List Display More Reader-Friendly
When you display a Model as a list, Django displays each record as the string representation of the record object, which in our case is "Member object (1)", "Member object(2)" etc.:


To change this to a more reader-friendly format, we have two choices:

Change the string representation function, __str__() of the Member Model
Set the list_display property of the MemberAdmin class
Change the String Representation Function
To change the string representation, we have to define the __str__() function of the Member Model in models.py, like this:

my_tennis_club/members/models.py:

from django.db import models

class Member(models.Model):
  firstname = models.CharField(max_length=255)
  lastname = models.CharField(max_length=255)
  phone = models.IntegerField(null=True)
  joined_date = models.DateField(null=True)

  def __str__(self):
    return f"{self.firstname} {self.lastname}"
 
 
Which gives us this result:


Defining our own __str__() function is not a Django feature, it is how to change the string representation of objects in Python. Read more about Python objects in our Python object tutorial.

Set list_display
We can control the fields to display by specifying them in a list_display property in the admin.py file.

First create a MemberAdmin() class and specify the list_display tuple, like this:

my_tennis_club/members/admin.py:

from django.contrib import admin
from .models import Member

# Register your models here.

class MemberAdmin(admin.ModelAdmin):
  list_display = ("firstname", "lastname", "joined_date",)
  
admin.site.register(Member, MemberAdmin)
 
Remember to add the MemberAdmin as an argument in the admin.site.register(Member, MemberAdmin).

--------------------------------------------------------------------------------------------------------------------------

Django Template Variables
Template Variables
In Django templates, you can render variables by putting them inside {{ }} brackets:

ExampleGet your own Django Server
templates/template.html:

<h1>Hello {{ firstname }}, how are you?</h1>
Create Variable in View
The variable firstname in the example above was sent to the template via a view:

views.py:

from django.http import HttpResponse
from django.template import loader

def testing(request):
  template = loader.get_template('template.html')
  context = {
    'firstname': 'Linus',
  }
  return HttpResponse(template.render(context, request))
As you can see in the view above, we create an object named context and fill it with data, and send it as the first parameter in the template.render() function.

Create Variables in Template
You can also create variables directly in the template, by using the {% with %} template tag.

The variable is available until the {% endwith %} tag appears:

Example
templates/template.html:

{% with firstname="Tobias" %}
<h1>Hello {{ firstname }}, how are you?</h1>
{% endwith %}
You will learn more about template tags in the next chapter.

Data From a Model
The example above showed a easy approach on how to create and use variables in a template.

Normally, most of the external data you want to use in a template, comes from a model.

We have created a model in the previous chapters, called Member, which we will use in many examples in the next chapters of this tutorial.

To get data from the Member model, we will have to import it in the views.py file, and extract data from it in the view:

members/views.py:

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Member

def testing(request):
  mymembers = Member.objects.all().values()
  template = loader.get_template('template.html')
  context = {
    'mymembers': mymembers,
  }
  return HttpResponse(template.render(context, request))
Now we can use the data in the template:

templates/template.html:

<ul>
  {% for x in mymembers %}
    <li>{{ x.firstname }}</li>
  {% endfor %}
</ul>
We use the Django template tag {% for %} to loop through the members.

You will learn more about template tags in the next chapter.

--------------------------------------------------------------------------------------------------------------------------
Template Tags
In Django templates, you can perform programming logic like executing if statements and for loops.

These keywords, if and for, are called "template tags" in Django.

To execute template tags, we surround them in {% %} brackets.

Tag Reference
A list of all template tags:

Tag	                Description
autoescape	        Specifies if autoescape mode is on or off
block	              Specifies a block section
comment	            Specifies a comment section
csrf_token	        Protects forms from Cross Site Request Forgeries
cycle	              Specifies content to use in each cycle of a loop
debug	              Specifies debugging information
extends	            Specifies a parent template
filter	            Filters content before returning it
firstof	            Returns the first not empty variable
for	                Specifies a for loop
if	                Specifies a if statement
ifchanged	          Used in for loops. Outputs a block only if a value has changed since the last iteration
include	            Specifies included content/template
load	              Loads template tags from another library
lorem	              Outputs random text
now	                Outputs the current date/time
regroup	            Sorts an object by a group
resetcycle	        Used in cycles. Resets the cycle
spaceless	Removes whitespace between HTML tags
templatetag	Outputs a specified template tag
url	Returns the absolute URL part of a URL
verbatim	Specifies contents that should not be rendered by the template engine
widthratio	Calculates a width value based on the ratio between a given value and a max value
with	Specifies a variable to use in the block

--------------------------------------------------------------------------------------------------------------------------

Django if Tag
If Statement
An if statement evaluates a variable and executes a block of code if the value is true.

Example
{% if greeting == 1 %}
  <h1>Hello</h1>
{% endif %} 

Elif
The elif keyword says "if the previous conditions were not true, then try this condition".

Example
{% if greeting == 1 %}
  <h1>Hello</h1>
{% elif greeting == 2 %}
  <h1>Welcome</h1>
{% endif %} 

Else
The else keyword catches anything which isn't caught by the preceding conditions.

Example
{% if greeting == 1 %}
  <h1>Hello</h1>
{% elif greeting == 2 %}
  <h1>Welcome</h1>
{% else %}
  <h1>Goodbye</h1>
{% endif %} 

Operators
The above examples uses the == operator, which is used to check if a variable is equal to a value, but there are many other operators you can use, or you can even drop the operator if you just want to check if a variable is not empty:

== : Is equal to.
!= : Is not equal to.
< : Is less than.
<= : Is less than, or equal to.
> : Is greater than.
>= : Is greater than, or equal to.
and : To check if more than one condition is true.
or : To check if one of the conditions is true.
and/or : Combine and and or.
in : To check if a certain item is present in an object.
not in : To check if a certain item is not present in an object.
is : Check if two objects are the same.
Note: This operator is different from the == operator, because the == operator checks the values of two objects, but the is operator checks the identity of two objects.
is not : To check if two objects are not the same.

--------------------------------------------------------------------------------------------------------------------------

Django for Tag
For Loops
A for loop is used for iterating over a sequence, like looping over items in an array, a list, or a dictionary.

ExampleGet your own Django Server
Loop through the items of a list:

{% for x in fruits %}
  <h1>{{ x }}</h1>
{% endfor %}
Example
Loop through a list of dictionaries:

{% for x in cars %}
  <h1>{{ x.brand }}</h1>
  <p>{{ x.model }}</p>
  <p>{{ x.year }}</p>
{% endfor %} 
Data From a Model
Data in a model is like a table with rows and columns.

The Member model we created earlier has five rows, and each row has three columns:

  id 	 firstname 	      lastname 	 phone 	 joined_date 
  1 	 Emil 	          Refsnes 	 5551234 	 2022-01-05 
  2 	 Tobias           Refsnes 	 5557777 	 2022-04-01 
  3 	 Linus 	          Refsnes 	 5554321 	 2021-12-24 
  4 	 Lene 	          Refsnes 	 5551234 	 2021-05-01 
  5 	 Stalikken 	      Refsnes 	 5559876 	 2022-09-29 
When we fetch data from the model, it comes as a QuerySet object, with a similar format as the cars example above: a list with dictionaries:

<QuerySet [
  {
    'id': 1,
    'firstname': 'Emil',
    'lastname': 'Refsnes',
    'phone': 5551234,
    'joined_date': datetime.date(2022, 1, 5)
  },
  {
    'id': 2,
    'firstname': 'Tobias',
    'lastname': 'Refsnes'
    'phone': 5557777,
    'joined_date': datetime.date(2021, 4, 1)
  },
  {
    'id': 3,
    'firstname': 'Linus',
    'lastname': 'Refsnes'
    'phone': 5554321,
    'joined_date': datetime.date(2021, 12, 24)
  },
  {
    'id': 4,
    'firstname': 'Lene',
    'lastname': 'Refsnes'
    'phone': 5551234,
    'joined_date': datetime.date(2021, 5, 1)
  },
  {
    'id': 5,
    'firstname': 'Stalikken',
    'lastname': 'Refsnes'
    'phone': 5559876,
    'joined_date': datetime.date(2022, 9, 29)
  }
]> 
Example
Loop through items fetched from a database:
{% for x in members %}
{% endfor %} 
Reversed
The reversed keyword is used when you want to do the loop in reversed order.

Example
{% for x in members reversed %}
{% endfor %}  
Empty
The empty keyword can be used if you want to do something special if the object is empty.

Example
<ul>
  {% for x in emptytestobject %}
  {% empty %}
  {% endfor %}
</ul> 
The empty keyword can also be used if the object does not exist:

Example
<ul>
  {% for x in myobject %}
  {% empty %}
  {% endfor %}
</ul> 
Loop Variables
Django has some variables that are available for you inside a loop:

forloop.counter : The current iteration, starting at 1.
forloop.counter0 : The current iteration, starting at 0.
forloop.first : Allows you to test if the loop is on its first iteration.
forloop.last : Allows you to test if the loop is on its last iteration.
forloop.parentloop : The current iteration if you start at the end and count backwards, ending up at 1.
forloop.revcounter : The current iteration if you start at the end and count backwards, ending up at 0.
forloop.revcounter0
forloop.counter


Example
<ul>
  {% for x in fruits %}
    <li>{{ forloop.counter }}</li>
  {% endfor %}
</ul> 
forloop.counter0


Example
<ul>
  {% for x in fruits %}
    <li>{{ forloop.counter0 }}</li>
  {% endfor %}
</ul> 
forloop.first


Example
Draw a blue background for the first iteration of the loop:

<ul>
  {% for x in fruits %}
    <li
      {% if forloop.first %}
        style='background-color:lightblue;'
      {% endif %}
    >{{ x }}</li>
  {% endfor %}
</ul> 
forloop.last

Example
Draw a blue background for the last iteration of the loop:

<ul>
  {% for x in fruits %}
    <li
      {% if forloop.last %}
        style='background-color:lightblue;'
      {% endif %}
    >{{ x }}</li>
  {% endfor %}
</ul> 
forloop.revcounter

Example
<ul>
  {% for x in fruits %}
    <li>{{ forloop.revcounter }}</li>
  {% endfor %}
</ul> 
forloop.revcounter0


Example
<ul>
  {% for x in fruits %}
    <li>{{ forloop.revcounter0 }}</li>
  {% endfor %}
</ul> 

--------------------------------------------------------------------------------------------------------------------------

Comments
Comments allows you to have sections of code that should be ignored.

ExampleGet your own Django Server
<h1>Welcome Everyone</h1>
{% comment %}
  <h1>Welcome ladies and gentlemen</h1>
{% endcomment %}
Comment Description
You can add a message to your comment, to help you remember why you wrote the comment, or as message to other people reading the code.

Example
Add a description to your comment:

<h1>Welcome Everyone</h1>
{% comment "this was the original welcome message" %}
    <h1>Welcome ladies and gentlemen</h1>
{% endcomment %}
Smaller Comments
You can also use the {# ... #} tags when commenting out code, which can be easier for smaller comments:

Example
Comment out the word Everyone:

<h1>Welcome{# Everyone#}</h1>

--------------------------------------------------------------------------------------------------------------------------

Include
The include tag allows you to include a template inside the current template.

This is useful when you have a block of content that is the same for many pages.

ExampleGet your own Django Server
templates/footer.html:

<p>You have reached the bottom of this page, thank you for your time.</p>
templates/template.html:

<h1>Hello</h1>

<p>This page contains a footer in a template.</p>

{% include 'footer.html' %} 
Variables in Include
You can send variables into the template by using the with keyword.

In the include file, you refer to the variables by using the {{ variablename }} syntax:

Example
templates/mymenu.html:
<div>HOME | {{ me }} | ABOUT | FORUM | {{ sponsor }}</div>
templates/template.html:

<!DOCTYPE html>
<html>
<body>

{% include "mymenu.html" with me="TOBIAS" sponsor="W3SCHOOLS" %}

<h1>Welcome</h1>

<p>This is my webpage</p>

</body>
</html> 


--------------------------------------------------------------------------------------------------------------------------


Django QuerySet
A QuerySet is a collection of data from a database.

A QuerySet is built up as a list of objects.

QuerySets makes it easier to get the data you actually need, by allowing you to filter and order the data at an early stage.

In this tutorial we will be querying data from the Member table.

Member:

  id 	 firstname 	lastname 	 phone 	 joined_date 
  1 	 Emil 	    Refsnes 	 5551234 	 2022-01-05 
  2 	 Tobias 	  Refsnes 	 5557777 	 2022-04-01 
  3 	 Linus 	    Refsnes 	 5554321 	 2021-12-24 
  4 	 Lene 	    Refsnes 	 5551234 	 2021-05-01 
  5 	 Stalikken 	Refsnes 	 5559876 	 2022-09-29 

Querying Data
In views.py, we have a view for testing called testing where we will test different queries.

In the example below we use the .all() method to get all the records and fields of the Member model:

ViewGet your own Django Server
views.py:

from django.http import HttpResponse
from django.template import loader
from .models import Member

def testing(request):
  mydata = Member.objects.all()
  template = loader.get_template('template.html')
  context = {
    'mymembers': mydata,
  }
  return HttpResponse(template.render(context, request))
The object is placed in a variable called mydata, and is sent to the template via the context object as mymembers, and looks like this:

<QuerySet [
  <Member: Member object (1)>,
  <Member: Member object (2)>,
  <Member: Member object (3)>,
  <Member: Member object (4)>,
  <Member: Member object (5)>
]>
--------------------------------------------------------------------------------------------------------------------------


Django QuerySet - Get Data
Get Data
There are different methods to get data from a model into a QuerySet.

The values() Method
The values() method allows you to return each object as a Python dictionary, with the names and values as key/value pairs:

ExampleGet your own Django Server
views.py:

from django.http import HttpResponse
from django.template import loader
from .models import Member

def testing(request):
  mydata = Member.objects.all().values()
  template = loader.get_template('template.html')
  context = {
    'mymembers': mydata,
  }
  return HttpResponse(template.render(context, request))
Return Specific Columns
The values_list() method allows you to return only the columns that you specify.

Example
Return only the firstname columns:

views.py:

from django.http import HttpResponse
from django.template import loader
from .models import Member

def testing(request):
  mydata = Member.objects.values_list('firstname')
  template = loader.get_template('template.html')
  context = {
    'mymembers': mydata,
  }
  return HttpResponse(template.render(context, request))
Return Specific Rows
You can filter the search to only return specific rows/records, by using the filter() method.

Example
Return only the records where firstname is 'Emil'

views.py:

from django.http import HttpResponse
from django.template import loader
from .models import Member

def testing(request):
  mydata = Member.objects.filter(firstname='Emil').values()
  template = loader.get_template('template.html')
  context = {
    'mymembers': mydata,
  }
  return HttpResponse(template.render(context, request))

--------------------------------------------------------------------------------------------------------------------------

Django QuerySet - Filter
QuerySet Filter
The filter() method is used to filter your search, and allows you to return only the rows that matches the search term.

As we learned in the previous chapter, we can filter on field names like this:
Example
Return only the records where the firstname is 'Emil': mydata = Member.objects.filter(firstname='Emil').values()
In SQL, the above statement would be written like this: SELECT * FROM members WHERE firstname = 'Emil';


AND
The filter() method takes the arguments as **kwargs (keyword arguments), so you can filter on more than one field by separating them by a comma.
Example
Return records where lastname is "Refsnes" and id is 2: mydata = Member.objects.filter(lastname='Refsnes', id=2).values()
In SQL, the above statement would be written like this: SELECT * FROM members WHERE lastname = 'Refsnes' AND id = 2;

OR
To return records where firstname is Emil or firstname is Tobias (meaning: returning records that matches either query, not necessarily both) is not as easy as the AND example above.)
We can use multiple filter() methods, separated by a pipe | character. The results will merge into one model.
Example
Return records where firstname is either "Emil" or Tobias": mydata = Member.objects.filter(firstname='Emil').values() | Member.objects.filter(firstname='Tobias').values()

Another common method is to import and use Q expressions:
Example
Return records where firstname is either "Emil" or Tobias": mydata = Member.objects.filter(Q(firstname='Emil') | Q(firstname='Tobias')).values()
In SQL, the above statement would be written like this: SELECT * FROM members WHERE firstname = 'Emil' OR firstname = 'Tobias';


Field Lookups
Django has its own way of specifying SQL statements and WHERE clauses.
To make specific where clauses in Django, use "Field lookups".
Field lookups are keywords that represents specific SQL keywords.

Example:
Use the __startswith keyword: .filter(firstname__startswith='L');
Is the same as the SQL statement: WHERE firstname LIKE 'L%'
The above statement will return records where firstname starts with 'L'.

Field Lookups Syntax
All Field lookup keywords must be specified with the fieldname, followed by two underscore characters, and the keyword.
Example
Return the records where firstname starts with the letter 'L': mydata = Member.objects.filter(firstname__startswith='L').values()

--------------------------------------------------------------------------------------------------------------------------

Order By
To sort QuerySets, Django uses the order_by() method 

Example
Order the result alphabetically by firstname: mydata = Member.objects.all().order_by('firstname').values()
In SQL, the above statement would be written like this:

SELECT * FROM members ORDER BY firstname;
Descending Order
By default, the result is sorted ascending (the lowest value first), to change the direction to descending (the highest value first), use the minus sign (NOT), - in front of the field name:

Example
Order the result firstname descending:

mydata = Member.objects.all().order_by('-firstname').values()
In SQL, the above statement would be written like this:

SELECT * FROM members ORDER BY firstname DESC;
Multiple Order Bys
To order by more than one field, separate the fieldnames with a comma in the order_by() method:

Example
Order the result first by lastname ascending, then descending on id:

mydata = Member.objects.all().order_by('lastname', '-id').values()
In SQL, the above statement would be written like this:

SELECT * FROM members ORDER BY lastname ASC, id DESC;


--------------------------------------------------------------------------------------------------------------------------

Django - Add Static File 
Create Static Folder
When building web applications, you probably want to add some static files like images or css files.

Start by creating a folder named static in your project, the same place where you created the templates folder:

The name of the folder has to be static.
Add a CSS file in the static folder, the name is your choice, we will call it myfirst.css in this example:
Open the CSS file and insert the following:

my_tennis_club/members/static/myfirst.css:

body {
  background-color: lightblue;
  font-family: verdana;
}
Modify the Template
Now you have a CSS file, with some CSS styling. The next step will be to include this file in a HTML template:

Open the templates/template.html file and add the following:

{% load static %}
And:

<link rel="stylesheet" href="{% static 'myfirst.css' %}">
ExampleGet your own Django Server
my_tennis_club/members/templates/template.html:

{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="{% static 'myfirst.css' %}">
<body>

{% for x in fruits %}
  <h1>{{ x }}</h1>
{% endfor %}

</body>
</html> 
 
Restart the server for the changes to take effect:

python manage.py runserver
And check out the result in your own browser: 127.0.0.1:8000/testing/.

Didn't Work?
Just testing? If you just want to play around, and not going to deploy your work, you can set DEBUG = True in the settings.py file, and the example above will work.

Plan to deploy? If you plan to deploy your work, you should set DEBUG = False in the settings.py file. The example above will fail, because Django has no built-in solution for serving static files, but there are other ways to serve static files, you will learn how in the next chapter.

Example (in development):
my_tennis_club/my_tennis_club/settings.py:

.
.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
.
.
This will make the example work, but we want you to choose DEBUG = False, because that is the best way to learn how to work with Django.

Choose Debug = False
For the rest of this tutorial, we will run with DEBUG = False, even in development, because that is the best way to learn how to work with Django.

Example:
my_tennis_club/my_tennis_club/settings.py:

.
.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']











































"""