# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/saisakthi/Coding-Project/Projects/Finished Projects/Docker/Terraform/infra/environments/terraform.tfstate"
  }
}
