-- Add migration script here
ALTER TABLE messages 
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users 
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE chat_rooms 
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE room_members 
    ALTER COLUMN last_seen_at TYPE TIMESTAMP WITHOUT TIME ZONE;
