# Html : hyper text markup language
# it is a skeletion language not a programming language
# it is markup language for websites and document
# it is building block of all website

# only index .html runs first in every website

# < : open tag
# > : close tag
# <> : inside the tag wher we type our command
# </> : inside this tag this is our command closes

# <h1> : it means heading , there are 6 heading
# <h2> , <h3> , <h4> <h5> <h6>

# <p> : it is used to write paragragh inside it , it has all the content
# <br> : used to break the paragraph and starts from next line [we can also use mn number odf times eg : if we wanted to leave 2 spaces , we can use <br><br>
#      : it doesn't have ending bracket
# eg : <p>Fruits are the means by which flowering plants (also known as angiosperms) disseminate their seeds.<br>
# Edible fruits in particular have long propagated using the movements of humans and other animals in a symbiotic relationship<BR>
# that is the means for seed dispersal for the one group and nutrition for the <br><br>
# humans and many other animals have become dependent on fruits as a source of food
#<br> Consequently, fruits account for a substantial for
# action of the world's agricultural output, and some (such as the apple and the pomegranate) have acquired extensive cultural and symbolic meanings.</p>

# <hr> : it creates a line between paragraph , it is used with either 2 <p> command or with <br> command
# eg : <p> hi bro i am sai </p>                      <p> i bro i am sai <br><hr.<br>
#    <hr>                                     [or]       i am studying 10 </p>
#     <p> i am studying 10 </p>

# <b> : if used it changes characters inside para bolder or darker
# eg : b>that is the means for seed dispersal for the one group and nutrition for the</b> <br><hr><br>

# <i> : if used it converts inside character tilted
# eg : <p><i>in botany, a fruit is the seed-bearing structure in flowering plant</i></p>

# <u> : if used it drawws ine underneath character
# eg : <p><u>that is formed from the ovary after flowering (see Fruit anatomy).</u></p>

# <a> : if used it consider everything under it specified as link and also convert any texts or image into links
#     : href is the function used to feed the link to the text or image
#     : if we wanted to open it in another tab we can use target = "blank" key before closing
# eg : <p><a href = "www.wikipedia.com/fruits" target = "blank"> To learn more</a></p>

# <img> [image] : used to insert image inside a html
#               : src is a fuction used to feed the source of image to display [it is like a navigator to the image to reach the imae wanted to display]
#               : width is a fuction that can be used to change the width of image
#               : alt is a function which is used if src location or image cannot be found
#               : it displays image
# eg : <img src = "hi.jpg" alt="image not found" width="100px">

# <iframe> ; it is used to cast another website inside our html [like screen casting wikipedia on our html]
#          : src is a fuction used to feed the source of image to display
#          : width is a fuction that can be used to change the width of image
# eg : <iframe src="https://en.wikipedia.org/wiki/Kumari_Kandam" width="500px"></iframe>


# list : ther ar etwo types of lists [ordered list and unordered list] it lists what we given in order

# <ol> [ordered list] : there is command <li> (full form <list>) [inside li we have to type what we want] after typing it prints what we wrote arranged in numerical orde [1,2,3]
# eg : <ol>
#    <li>apple</li>
#    <li>orange</li>
#    <li>pineapple</li>
#    <li>dragonfruit</li>
#</ol>

# <ul> : there is command <li> (full form <list>) [inside li we have to type what we want] after typing it prints what we wrote arranged in bulletin order [.,.,.]

# <table> : there are many keyword inside table
# <thead> [table head] : it is used to create table head [upper part or heading part]
# <tr> [table row] : it is ude to create rows for table

# <form> : it is used to create a interactive button and whd when used it either loads another page or verify passwords
#        : there are sub titles can be used


# action = : if used it loads the page specified [ eg : To learn more button]
# method = : if used it verify input from user to server [ eg : login button]

# eg :
# <form action = "next.php" method = "POST"></form>

# project 1 : <!DOCTYPE html>
#<html lang="en">
#<head>
#    <meta charset="UTF-8">
#    <title>Website About Fruit</title>
#    <center>Fruits</center>
#</head>
#<body>
#<h1>Fruits</h1>
#<p><i>in botany, a fruit is the seed-bearing structure in flowering plant</i></p>
#<p><u>that is formed from the ovary after flowering (see Fruit anatomy).</u></p>
#<p>Fruits are the means by which flowering plants (also known as angiosperms) disseminate their seeds.<br>
#<p> Edible fruits in particular have long propagated using the movements of humans and other animals in a symbiotic relationship</p>
#    <b>that is the means for seed dispersal for the one group and nutrition for the</b> <br><hr><br>
#humans and many other animals have become dependent on fruits as a source of food <br>
#Consequently, fruits account for a substantial fraction of the world's agricultural output, and some (such as the apple and the pomegranate) have acquired extensive cultural and symbolic meaning
#<p><a href = "www.wikipedia.com/fruits" target = "blank"> To learn more</a></p>
#
#<!-- list-->
#
#<ol>
#    <li>apple</li>
#    <li>orange</li>
#    <li>pineapple</li>
#    <li>dragonfruit</li>
#</ol>
#<ul>
#    <li>apple</li>
#    <li>orange</li>
#    <li>pineapple</li>
#    <li>dragonfruit</li>
#</ul>
#
#<!--table-->
#
#<table>
#    <thead>
#        <tr>
#            <th>User</th>
#            <th>Email</th>
#            <th>Password</th>
#        </tr>
#    </thead>
#    <tbody>
#        <tr>
#           <td>Sai</td>
#            <td>saisai@gmail.com</td>
#            <td>Saisai</td>
#        </tr>
#    </tbody>
#    <tbody>
#        <tr>
#           <td>Sakthi</td>
#            <td>sakthi@gmail.com</td>
#            <td>Saisakthi</td>
#        </tr>
#    </tbody>
#</table>
#<!--form-->
#<br><br>
#<div>
#<form action = "next.php" method = "POST"></form>
#    <label>Type A Fruit</label>
#    <input type = "text" name = "name"></div>
#<div><br>
#    <label>Type A Fruit (Number)</label>
#    <input type = "number" name = "name"></div>
#
#<div>
#<form action = "next.php" method = "POST"></form>
#    <label>Type A Fruit (password)</label>
#    <input type = "password" name = "pname"></div>
#
#<!--button-->
#
#<button>Fruits</button>
#</body>
#</html>