services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_DB=notesdb
      - POSTGRES_USER=saisakthi
      - POSTGRES_PASSWORD=saisakthi2008
      - DB_HOST=notes-postgres
    depends_on:
      - notes-postgres
    container_name: notes-backend
    networks:
      - notes-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: notes-frontend
    depends_on:
      - backend
    networks:
      - notes-net

  notes-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: saisakthi
      POSTGRES_PASSWORD: saisakthi2008
    container_name: notes-postgres
    volumes:
      - notes_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - notes-net
    

  notes-nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    container_name: notes-nginx
    depends_on:
      - backend
    networks:
      - notes-net

networks:
  notes-net:
    driver: bridge

volumes:
  notes_pgdata:
