server {
    listen 80;
    client_max_body_size 1000M;
    server_name localhost;

    resolver 127.0.0.11 valid=30s ipv6=off;

    location /notes/api/ {
        set $upstream http://notes-backend:8000;
        proxy_pass $upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
    }

    location /notes/ {
        root /apps;
        try_files $uri $uri/ /notes/index.html;
    }

    location /bank/api/ {
        set $upstream http://bank-backend:8080;
        proxy_pass $upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
    }

    location /bank/ {
        root /apps;
        try_files $uri $uri/ /bank/index.html;
    }

    location /quiz/ {
        root /apps;
        try_files $uri $uri/ /quiz/index.html;
    }

    location /video/api/ {
        set $upstream http://video-uploader-backend:8080;
        proxy_pass $upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
    }

    location /video/ {
        root /apps;
        try_files $uri $uri/ /video/index.html;
    }

    location /hospital/ {
        set $upstream http://hospital-management:8000;
        proxy_pass $upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
    }

    location /blog/ {
        set $upstream http://blog-website:8000;
        proxy_pass $upstream/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
    }

    location /social/ {
        set $upstream http://172.18.0.2:30080;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
    }

    location / {
        return 200 '{"status":"gateway running","apps":["/notes/","/bank/","/quiz/","/video/","/hospital/","/blog/","/social/"]}';
        add_header Content-Type application/json;
    }
}