server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers: {}

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

storage:
  trace:
    backend: s3
    s3:
      endpoint: minio:9000
      bucket: media
      access_key: minio
      secret_key: minio123
      insecure: true

compactor:
  compaction:
    block_retention: 168h
